[target.x86_64-unknown-linux-gnu]

# recent mold
#linker = "clang"
#rustflags = ["-C", "link-arg=--ld-path=/home/pierretienne/dev/sources/mold/build/mold"]

# recent wild
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]

# default system linker
#rustflags = ["-Clinker-features=-lld"]

# old apt mold
#rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]

# apt lld
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]
